image: registry.conci.info/conci/image/base:master

before_script:
  - cp codeception-lumen.yml codeception.yml
  - composer install
  - composer require --dev laravel/lumen-framework:5.* --no-interaction
  - php tests/replace_autoload.php

# Test
test:
  script:
    - php -dzend_extension=xdebug.so ./vendor/bin/codecept run --coverage-text