image: registry.conci.info/jobsy/backend/fpm:master

before_script:
  - cp codeception-lumen.yml codeception.yml
  - composer install
  - composer require --dev laravel/lumen-framework:5.* --no-interaction

# Test
test:
  script:
    - php -dzend_extension=xdebug.so ./vendor/bin/codecept run  --coverage --coverage-text --coverage-xml