image: php:7.1

cache:
  paths:
    - vendor/

before_script:
  # Install all project dependencies
  # Install git and unzip (composer will need them)
  - apt-get update && apt-get install -qqy git unzip
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  # Install composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  # Install all project dependencies
  - cp codeception-lumen.yml codeception.yml
  - composer install
  - composer require --dev laravel/lumen-framework:5.* --no-interaction

# Test
test:
  script:
    - vendor/bin/codecept run --coverage