language: php
php:
  - 7.1
  - 7.2
matrix:
  fast_finish: true
sudo: true
cache:
  directories:
    - vendor
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
script:
  - bash run-tests.sh
after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage/coverage.clover